### PR TITLE
Updated drivers for Linux 6.8.9

### PR DESCRIPTION
**Pull request by gonsolo**
I don't expect this to be merged as I cleaned up a lot of stuff which is probably unnecessary but at least future programmers will have a reference to an up-to-date and *working* XDMA driver!

### CODE REVIEW

**Comment by makslevental** [comment]
Umm why did you move/delete stuff? It's pretty hard to tell what the diff is...

**Comment by gonsolo** [comment]
> Umm why did you move/delete stuff? It's pretty hard to tell what the diff is...

It's probably easiest to check it out somewhere else and diff the xdma/xvsec directories.

Sorry about the mess, the redundant XDMA/linux_kernel/xdma typing made me ... unhappy.

(And nothing of this would have been necessary if AMD kept their drivers updated or upstream in the kernel.)

**Comment by gonsolo** [comment]
BTW: I have a design with a Nitefury II running, but XDMA can only find the config bar if the kernel is booted with `pci=nomsi` and the xdma kernel module is inserted with `sudo modprobe xdma poll_mode=1 interrupt_mode=2`. I haven't looked into this further as everything is running now, but it would be nice if XDMA would work in MSI (default) mode with interrupts too.

**Comment by hinxx** [comment]
> it would be nice if XDMA would work in MSI (default) mode with interrupts too.

It does. We're using MSI & interrupts without any issues.

**Comment by gonsolo** [comment]
> > it would be nice if XDMA would work in MSI (default) mode with interrupts too.
> It does. We're using MSI & interrupts without any issues.

Ok. Can you think of a reason why the config bar can't be found as soon as I change one of the parameters, kernel `pci=nomsi` and xdma module `poll_mode=1 interrupt_mode=2`?

**Comment by hinxx** [comment]
> Can you think of a reason why the config bar can't be found as soon as I change one of the parameter

No, I can't. It's likely to do with the IP core config or something. But I'm no firmware developer, so..

On a related note, someone posted a nice step-by-step tutorial on IP core config that might be of use for you; browse through the issues here it was not long ago.

**Comment by gonsolo** [comment]
> > Can you think of a reason why the config bar can't be found as soon as I change one of the parameter
> No, I can't. It's likely to do with the IP core config or something. But I'm no firmware developer, so..

Ok.

> On a related note, someone posted a nice step-by-step tutorial on IP core config that might be of use for you; browse through the issues here it was not long ago.

I search the issues but didn't find that tutorial. :( But thanks anyways.

**Comment by Unlicensed-driver-ljx** [comment]
@gonsolo 能分享一下驱动程序吗，祝你工作顺利

**Comment by gonsolo** [comment]
> 能分享一下驱动程序吗，祝你工作顺利

It's here in my branch: https://github.com/gonsolo/dma_ip_drivers/tree/gonsolo
It works on the latest kernel (6.10.9), and in the README are instructions how I finally got it to find the config bar.

**Pull request closed without merging**
