### PR TITLE
Mark dma_memory_mapped_test.sh as executable

### PR DESCRIPTION
**Pull request by ted-xie**
Otherwise run_test.sh fails on ./dma_memory_mapped_test.sh.

### CODE REVIEW

**Comment by ted-xie** [comment]
@codypiersall I do see activity in this repository but no one has reviewed this PR. It does seem strange that the Xilinx scripts try to directly execute these scripts but they are not marked as executable.

**Comment by codypiersall** [comment]
I guess the only recourse left is to leave comments that say "ping" about once a month for the rest of eternity... I for one am looking forward to it.

**Comment by hmaarrfk** [comment]
Post on their official forums

**Comment by ted-xie** [comment]
This PR has been open for two years now, and I'm still perplexed that Xilinx/AMD itself hasn't run into the issues with the `exec` bit not being set for these scripts. Can we get a review, or just close the PR? Maybe @ssangani-xlnx?

**Comment by ted-xie** [comment]
This PR has been sitting stale for long enough, and it's quite evident that Xilinx does not think it is worth merging.

**Pull request closed without merging**
